name: chroot riscv64/alpine

on:
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -ex
          uname -a
          id
          pwd
          cd ~
          pwd
          wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          export GITHUB_ACTIONS=true
          ./ppkg setup
          ./ppkg update
          ./ppkg install uctags --static
          ./ppkg pack    uctags
          EOF

      - run: curl -LO https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -d /alpine -a riscv64 -p wget -p g++
      - run: /alpine/enter-chroot sh run.sh
      - run: /alpine/destroy
      - run: ls -l /alpine/
      - run: ls -l /alpine/root
      - run: ls -l /alpine/root/.ppkg

      - uses: actions/upload-artifact@v4
        with:
          name: uctags---linux-riscv64.tar.xz
          path: /alpine/root/uctags-*-linux-riscv64.tar.xz
