name: chroot alpine/armv7l

on:
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > test.c <<EOF
          #include <time.h>
          #include <stdio.h>

          int main() {
            char ts[20];

            time_t t = time(NULL);

            int ret;

            if (sizeof(t) == sizeof(long)) {
              ret = snprintf(ts, 20, "%ld", t);
            } else if (sizeof(t) == sizeof(long long)) {
              ret = snprintf(ts, 20, "%lld", t);
            }

            if (ret < 0) {
                perror(NULL);
                return 1;
            }

            puts(ts);

            return 0;
          }
          EOF

      - run: |
          cat > run.sh <<EOF
          set -ex
          uname -a
          id
          pwd

          gcc test.c
          ./a.out
          EOF

      - run: curl -LO https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -d /alpine -a armhf -p wget -p g++
      - run: /alpine/enter-chroot sh run.sh
      - run: /alpine/destroy
      - run: ls -l
