name: chroot ubuntu/s390x

on:
  workflow_dispatch:

jobs:
  chroot_qemu:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
      - run: |
          cat > test.c <<EOF
          #include<stdio.h>
          int main() {
            puts("HELLO");
            return 0;
          }
          EOF

      - run: |
          cat > run.sh <<EOF
          set -ex
          uname -a
          id
          pwd

          apt -y update
          apt -y install curl xz-utils ${{ matrix.compiler }}

          ${{ matrix.compiler }} test.c
          readelf -h a.out
          EOF

      - run: sudo apt-get -y update
      - run: sudo apt-get -y install qemu-user-static

      - run: curl -LO https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.2-base-s390x.tar.gz

      - run: install -d ubuntu-rootfs
      - run: tar xf ubuntu-base-24.04.2-base-*.tar.gz -C ubuntu-rootfs

      - run: cp -p /etc/resolv.conf ubuntu-rootfs/etc/
      - run: mv run.sh ubuntu-rootfs/

      - run: sudo mount -o bind  /dev ubuntu-rootfs/dev
      - run: sudo mount -t proc  none ubuntu-rootfs/proc
      - run: sudo mount -t sysfs none ubuntu-rootfs/sys
      - run: sudo mount -t tmpfs none ubuntu-rootfs/tmp

      - run: sudo install -g `id -g` -o `id -u` /usr/bin/qemu-s390x-static ubuntu-rootfs/

      - run: sudo chroot ubuntu-rootfs /qemu-s390x-static /bin/sh run.sh
