name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - name: setup locallib
        run: |
          wget https://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-2.000024.tar.gz
          tar zxvf local-lib-2.000024.tar.gz
          cd local-lib-2.000024

          PERL_LOCAL_LIB_ROOT=$GITHUB_WORKSPACE/perl5

          perl Makefile.PL --bootstrap=$PERL_LOCAL_LIB_ROOT
          make
          make test

          echo >> "$GITHUB_ENV" <<EOF
          PERL_LOCAL_LIB_ROOT="$PERL_LOCAL_LIB_ROOT"
          PERL5LIB="\$PERL_LOCAL_LIB_ROOT/lib/perl5"
          PERL_MB_OPT="--install_base \"\$PERL_LOCAL_LIB_ROOT/\""
          PERL_MM_OPT="INSTALL_BASE=\$PERL_LOCAL_LIB_ROOT"
          PATH="\$PERL_LOCAL_LIB_ROOT/bin:\$PATH"
          EOF

          cat "$GITHUB_ENV"
          ls "$PERL_LOCAL_LIB_ROOT"

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg

      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg env

      - run: ./ndk-pkg update

        #- run: cp basis_universal.sh ~/.ndk-pkg/repos.d/offical/formula

      - run: ./ndk-pkg install fortune --tree
