name: cpan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - run:  brew install tree

      - run:  sudo cpan -i App::Docmake

      - name: setup locallib
        run: |
          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          run() {
            printf '%b\n' "$COLOR_PURPLE==>$COLOR_OFF $COLOR_GREEN$*$COLOR_OFF"
            eval "$*"
          }

          run wget https://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-2.000024.tar.gz
          run tar zxvf local-lib-2.000024.tar.gz
          run cd local-lib-2.000024

          PERL_LOCAL_LIB_ROOT=$GITHUB_WORKSPACE/perl5

          run perl Makefile.PL --bootstrap=$PERL_LOCAL_LIB_ROOT
          run make
          run make test
          #run make install

          printf '%s\n' "
          PERL_LOCAL_LIB_ROOT='$PERL_LOCAL_LIB_ROOT'
          PERL5LIB='$PERL_LOCAL_LIB_ROOT/lib/perl5'
          PERL_MB_OPT='--install_base $PERL_LOCAL_LIB_ROOT/'
          PERL_MM_OPT='INSTALL_BASE=$PERL_LOCAL_LIB_ROOT'
          PATH='$PERL_LOCAL_LIB_ROOT/bin:$PATH'
          " >> "$GITHUB_ENV"

          run cat "$GITHUB_ENV"
          run tree "$PERL_LOCAL_LIB_ROOT"

      - run: |
          env | grep ^PERL

      - run: cpan -i App::Cpan
      - run: cpan -i Path::Tiny
      - run: cpan -i App::Docmake

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg

      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg env

      - run: ./ndk-pkg update

        #- run: cp basis_universal.sh ~/.ndk-pkg/repos.d/offical/formula

        #- run: ./ndk-pkg install fortune --tree
