name: docker riscv64/ubuntu

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          apt-get -y update
          EOF

      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:/root -w /root --name ubuntu riscv64/ubuntu:20.04 sh run.sh
