name: docker alpine

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['3.12', '3.13', '3.14', '3.15', '3.16', '3.17', '3.18', '3.19', '3.20', latest, edge]
        target-arch: [x86_64, aarch64, ppc64le, riscv64, s390x]
 
    steps:
      - run: |
          cat > run.sh <<EOF
          apk update
          apk add gcc
          EOF

      # https://github.com/multiarch/qemu-user-static
      - if: matrix.target-arch != 'x86_64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - if: matrix.target-arch == 'x86_64'
        run: docker run -v $PWD:/root -w /root --name alpine         alpine:${{ matrix.version }} sh run.sh

      - if: matrix.target-arch == 'aarch64'
        run: docker run -v $PWD:/root -w /root --name alpine arm64v8/alpine:${{ matrix.version }} sh run.sh

      - if: matrix.target-arch == 'ppc64le'
        run: docker run -v $PWD:/root -w /root --name alpine ppc64le/alpine:${{ matrix.version }} sh run.sh

      - if: matrix.target-arch == 'riscv64'
        run: docker run -v $PWD:/root -w /root --name alpine riscv64/alpine:${{ matrix.version }} sh run.sh

      - if: matrix.target-arch == 's390x'
        run: docker run -v $PWD:/root -w /root --name alpine   s390x/alpine:${{ matrix.version }} sh run.sh
