name: DragonFlyBSD sizeof clockid_t

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['6.4.0']

    steps:
      - uses: actions/checkout@v4

      - run: |
          cat > test.c <<EOF
          #include<time.h>
          #include<stdio.h>
          int main() {
            printf("%ld\n", sizeof(clockid_t));
            return 0;
          }
          EOF

      - run: ls

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            set -ex
            uname -s
            uname -m
            uname -r
            cat /etc/os-release
            id
            cc test.c
            ./a.out
            cc -E test.c
