name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        version: [12]
    
    env:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/freebsd${{ matrix.version }}
          run: |
            run pkg install -y rsync
