# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        version: [13]

    env:
      VAGRANT_LOG: debug

    steps:
      - run:  vagrant --version

      - uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - run: |
          if [ -d ~/.vagrant.d ] ; then
            ls ~/.vagrant.d
          fi

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/freebsd${{ matrix.version }}
          run: |
            #run pkg install -y git
            echo xx
