# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        version: [13]

    env:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - run:  vagrant --version
      - run:  rm -rf ~/.vagrant.d

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/freebsd${{ matrix.version }}
          run: |
            run pkg install -y git
