name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]
    
    steps:
      - uses: actions/checkout@v2
      - run:  vagrant plugin install vagrant-scp

      - run:  vagrant init generic/freebsd${{matrix.version}}

      - name: gen shell.sh
        run: |
          printf 'set -e\n' > shell.sh
          export -p | grep 'GITHUB_' >> shell.sh
          cat >> shell.sh <<EOF
          run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            eval "$*"
          }

          run cd /home/vagrant/${{github.repository}}

          run pwd
          run ls

          run id

          run pkg install -y curl

          run curl -LO https://raw.githubusercontent.com/leleliu008/zpkg/master/bin/zpkg

          run chmod +x zpkg

          run ./zpkg env
          run ./zpkg update
          run ./zpkg install base64
          EOF

      - name: gen Vagrantfile
        run: |
          cat > Vagrantfile <<EOF
            Vagrant.configure("2") do |config|
              config.vm.box = "generic/freebsd${{matrix.version}}"
              config.vm.provider "virtualbox" do |vb|
                vb.memory = "2048"
              end
              config.vm.synced_folder "${{github.workspace}}", "/home/vagrant/${{github.repository}}", type: "rsync"
              config.vm.provision "shell", path: "shell.sh"
            end
          EOF

      - run: cat Vagrantfile
      - run: cat shell.sh

      - run: vagrant up
      - run: vagrant provision

      - run: vagrant scp :/home/vagrant/.zpkg/binary.d/ .

      - run: ls
