name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]
    
    env:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - run:  vagrant init generic/freebsd${{matrix.version}}

      - name: gen shell.sh
        run: |
          printf 'set -e\n' > shell.sh
          export -p | grep 'GITHUB_' >> shell.sh
          cat >> shell.sh <<'EOF'
          run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            eval "$*"
          }

          run cd /home/vagrant/${{github.repository}}

          run pwd
          run ls

          run id

          run pkg install -y curl

          run curl -LO https://raw.githubusercontent.com/leleliu008/zpkg/master/bin/zpkg

          run chmod +x zpkg

          run ./zpkg env
          run ./zpkg update

          for item in base64 cmake gmake gsed gawk gtar gzip xz bzip2 lzip p7zip zip unzip tree
          do
            run ./zpkg install $item
            run ./zpkg tree $item
            run ./zpkg pack $item
          done
          EOF

      - name: gen Vagrantfile
        run: |
          cat > Vagrantfile <<EOF
            Vagrant.configure("2") do |config|
              config.vm.box = "generic/freebsd${{matrix.version}}"
              config.vm.provider "virtualbox" do |vb|
                vb.memory = "2048"
              end
              config.vm.synced_folder "${{github.workspace}}", "/home/vagrant/${{github.repository}}", type: "rsync"
              config.vm.provision "shell", path: "shell.sh"
            end
          EOF

      - run: cat Vagrantfile
      - run: cat shell.sh

      - run: vagrant up --provision
      - run: vagrant ssh-config

      - run: scp -i .vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/root/.zpkg/binary.d .

      - run: ls
      - run: ls binary.d

      - run: printf '%s\n' "$RELEASE_TOKEN" | gh auth login --with-token
      - run: gh release create $(date +%Y%m%d) $(ls binary.d/*) --notes 'new release'
