name: Gentoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: madhacking/gentoo

    steps:
      - run: emerge dev-vcs/git

      - uses: actions/checkout@v2

      - run: emerge -s "%^cmake$"
      - run: emerge -s "%^make$"
      - run: emerge -s "%^git$"

      - run: emerge -s "%@^dev-vcs/git$"
      - run: emerge -s "%^kkkhhggff$"
