# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: Gentoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: madhacking/gentoo

    steps:
      - run: |
          install -d /etc/portage/binrepos.conf
          cat >      /etc/portage/binrepos.conf/gentoobinhost.conf <<EOF
          [binhost]
          priority = 9999
          sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/
          EOF

      - run: emerge -g -K -v dev-vcs/git

      - uses: actions/checkout@v4

      - run: emerge -s "%^cmake$"
      - run: emerge -s "%^make$"
      - run: emerge -s "%^git$"

      - run: emerge -s "%@^dev-vcs/git$"
      - run: emerge -s "%^kkkhhggff$"

      - run: |
          emerge -s "%^cmake$" | sed -n '/Latest version available:/p' | cut -d: -f2
      - run: |
          emerge -s "%^make$"  | sed -n '/Latest version available:/p' | cut -d: -f2
      - run: |
          emerge -s "%^git$"   | sed -n '/Latest version available:/p' | cut -d: -f2
