name: graphql

on:
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - run: |
          cat > QUERY <<EOF
          {
            repository(owner: "leleliu008", name: "uppm") {
                latestRelease {
                  name
                }
            }
          }
          EOF
          cat QUERY
          gh api graphql -f "query=$(cat QUERY)"
          #--jq .data.repository.latestRelease.name
