name: publish golang

on:
  workflow_dispatch:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest

    container: alpine:3.18

    steps:
      - run: wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install golang --link-type=static-only --install-lib=static
      - run: ./ppkg pack    golang -o .

      - uses: actions/upload-artifact@v3
        with:
          name: golang---linux-x86_64-tar-xz
          path: golang-*.tar.xz
