# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: DragonFlyBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['6.4.0']

    steps:
      - uses: actions/checkout@v4

      - run: ls

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}"
          usesh: true
          sync: rsync
          copyback: true
          prepare: |
            set -x
            id
            pwd
            ls
            touch hahaha.txt

      - run: ls
