# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: GragonFlyBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        version: [6]

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/dragonflybsd${{ matrix.version }}
          run: |
            run pkg update
            run pkg install -y gmake
