name: build libcurl for linux-musl-s390x

on:
  workflow_dispatch

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        version: [ '8.9.1' ]

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run apk update
          run apk add wget pkgconf make gcc libc-dev linux-headers nghttp2-dev openssl-dev zlib-dev

          run wget https://curl.haxx.se/download/curl-${{ matrix.version }}.tar.bz2
          run tar vxf curl-${{ matrix.version }}.tar.bz2 --strip-components 1
          run ./configure --with-default-ssl-backend=openssl
          run make --jobs=3
          EOF

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v "$PWD:/root" -w /root s390x/alpine:3.15 sh run.sh
