# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [14]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: https://github.com/leleliu008/ndk-pkg/releases/download/ndk-pkg-core-2024.05.15/ndk-pkg-core-2024.05.15-macos-14.0-arm64.tar.xz
      - run: tar vxf ndk-pkg-core-2024.05.15-macos-14.0-arm64.tar.xz --strip-components=1
      - run: ./uppm setup
      - run: ./uppm update
      - run: ls ~/.uppm/repos.d/official-core/formula/
      - run: ./uppm install docbook-xsl
