# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS-brew-test

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [11,12,13]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: df -h
      - run: brew install automake pkg-config jansson libyaml libxml2 pcre2
      - run: pip3 install docutils
