# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [10.15, 11, 12]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: curl -LO https://github.com/leleliu008/uppm-package-repository-macos-x86_64/releases/download/2022.11.10/uppm-2022.11.08-macos-x86_64.tar.xz
      - run: ./uppm update
      - run: ./uppm install cmake
      - run: ./uppm install git
      #- run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
      #- run: chmod a+x ppkg
      #- run: ./ppkg setup
