name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg

      - run: chmod +x ndk-pkg
  
      - run: ./ndk-pkg env

      - run: ./ndk-pkg update

        #- run: cp tesseract.sh ~/.ndk-pkg/repos.d/offical/formula

      - run: ./ndk-pkg install libnl --tree
