# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [11,12,13,14]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-macos-14.0-arm64.tar.xz
      - run: tar vxf ppkg-0.1000.2-macos-14.0-arm64.tar.xz
