# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [11]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: adnanh/webhook

      - run: go env

      - run: cat go.mod

      - run: install -d out/

      - run: go get -u golang.org/x/sys

      - run: cat go.mod

      - run: go mod vendor

      - run: go build -v -ldflags '-s -w' -o out/

      - run: ls out/
