# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macos-11-cmake

on:
  workflow_dispatch:

jobs:
  test1:

    runs-on: macos-11

    steps:
      - run: curl -LO https://github.com/Kitware/CMake/releases/download/v3.29.3/cmake-3.29.3-macos-universal.tar.gz
      - run: tar vxf cmake-3.29.3-macos-universal.tar.gz --strip-components=1

      - run: |
          cat > test.cmake <<EOF
          function(re2c_bootstrap_lexer input output)
              message("ARGV=\${ARGV}")
              message("ARGN=\${ARGN}")
          endfunction()

          re2c_bootstrap_lexer(1 2)
          re2c_bootstrap_lexer(1 2 3)
          EOF

      - run: CMake.app/Contents/bin/cmake --version
      - run: CMake.app/Contents/bin/cmake -P test.cmake

  test2:

    runs-on: macos-11

    steps:
      - run: curl -LO https://github.com/leleliu008/uppm-package-repository-macos-11.0-x86_64/releases/download/2024.06.01/cmake-3.29.3-macos-11.0-x86_64.tar.xz
      - run: tar vxf cmake-3.29.3-macos-11.0-x86_64.tar.xz --strip-components=1

      - run: |
          cat > test.cmake <<EOF
          function(re2c_bootstrap_lexer input output)
              message("ARGV=\${ARGV}")
              message("ARGN=\${ARGN}")
          endfunction()

          re2c_bootstrap_lexer(1 2)
          re2c_bootstrap_lexer(1 2 3)
          EOF

      - run: bin/cmake --version
      - run: bin/cmake -P test.cmake
