name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      #- uses: actions/checkout@v2
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/zpkg/master/bin/zpkg

      - run: chmod +x zpkg
     
      - run: ./zpkg env
      - run: command -v nproc
      - run: nproc
      - run: ./zpkg nproc -x

      - run: ./zpkg update

      - run: ./zpkg install zlib --tree --pack -x
    
      - run: |
          ls -a .
          cp -r . ..
          ls -a ..
