# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: brew update
      - run: brew list
      - run: brew install automake pkg-config bash libxml2 jansson libyaml gdb docutils pcre2
      - run: brew install bison
      - run: brew --prefix bison
      - run: |
          brew info --json=v2 bison | sed -n '/"keg_only":/p'
      - run: |
          brew info --json=v2 bison | sed -n '/"keg_only:"/p' | sed 's/ //g' | cut -d: -f2 | sed 's/,//'
      - run: |
          ls $(brew --prefix bison)

      - run: cc -dumpmachine
      - run: cc --version

      - run: clang --version
      - run: clang -dumpmachine

      - run: curl -LO https://fossies.org/linux/misc/tiff-4.4.0.tar.gz

        #- uses: actions/checkout@v2

        #- run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/dev/bin/ndk-pkg

        #- run: chmod +x ndk-pkg
  
        #- run: ./ndk-pkg env

        #- run: ./ndk-pkg update

        #- run: cp bitcoin.sh ~/.ndk-pkg/repos.d/offical/formula

        #- run: ./ndk-pkg install icu4c

        #- run: hexdump -n 20 -v -e '1/1 "%02X" "/"' ~/.ndk-pkg/install.d/android/21/icu4c/armeabi-v7a/lib/libicudata.so
