# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  good:

    runs-on: macos-12

    steps:
      - run: brew update
      - run: brew install --overwrite python@3.10 python@3.11

      - run: brew update
      - run: brew install python3

  bad:

    runs-on: macos-12

    steps:
      - run: brew update
      - run: brew install --overwrite python@3.10 python@3.11

      - run: brew install python3
