# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: macOS-brew-test

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [14]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: df -h
      - run: brew info usbmuxd --json
      - run: brew info usbmuxd --json | jq '.[0].versions.stable'
