name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      #- uses: actions/checkout@v2
      #- run: curl -LO https://raw.githubusercontent.com/leleliu008/zpkg/master/bin/zpkg

      #- run: chmod +x zpkg
     
      #- run: ./zpkg env
      #- run: ./zpkg nproc

      #- run: ./zpkg update

        #- run: ./zpkg install zlib --tree --pack -x
    
      - run: brew info --json cmake
      - run: brew info --json  make
      - run: brew info --json   git

      - run: brew info cmake
      - run: brew info make
      - run: brew info git

      - run: |
          brew info cmake | sed -n '/^cmake:/p'
      - run: |
          brew info make  | sed -n '/^make:/p'
      - run: |
          brew info git   | sed -n '/^git:/p'

      - run: |
          brew info cmake | sed -n '/^cmake:/p' | cut -d ' ' -f3
      - run: |
          brew info make  | sed -n '/^make:/p'  | cut -d ' ' -f3
      - run: |
          brew info git   | sed -n '/^git:/p'   | cut -d ' ' -f3
