name: build with Vistual Studio / MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        version: [windows-2022, windows-2019]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.version }}

    defaults:
      run:
        shell: cmd /C {0}

    steps:
      - run: choco install -y file

      - uses: actions/checkout@v3
        with:
          repository: 'universal-ctags/ctags'

      - name: build ctags with msbuild
        run: |
          @echo on

          copy win32\config_mvc.h config.h
          copy win32\gnulib_h\langinfo.h gnulib
          copy win32\gnulib_h\fnmatch.h gnulib

          cd win32

          if "${{ matrix.version }}" == "windows-2019" (
            set "XX= (x86)"
          ) else (
            set "XX="
          )

          set "MSBUILD=C:\Program Files%XX%\Microsoft Visual Studio\${{ matrix.version }}\Enterprise\MSBuild\Current\Bin\msbuild.exe"

          %MSBUILD% ctags_vs2013.sln /p:Configuration=${{ matrix.configuration }}

      - run: dir

      - run: file ${{ matrix.configuration }}\ctags.exe
      - run: ${{ matrix.configuration }}\ctags.exe --version
