# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        #msystem: [MSYS, MINGW32, MINGW64, CLANG32, CLANG64]
        msystem: [CLANG32]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: git
        pacboy: toolchain:p python-sphinx:p jansson:p libxml2:p libyaml:p pcre2:p

    - run: pacman -S --noconfirm mingw-w64-i686-jansson
