name: ndk-pkg

on:
  workflow_dispatch:

jobs:
  alpine:
 
    runs-on: ubuntu-latest

    container: alpine

    steps:
      - run: wget https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg setup
      - run: ./ndk-pkg about
      - run: ./ndk-pkg update
      - run: ./ndk-pkg install android-35-arm64-v8a/rav1e -x-cargo --static

  ubuntu:
 
    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg setup
      - run: ./ndk-pkg about
      - run: ./ndk-pkg update
      - run: ./ndk-pkg install android-35-arm64-v8a/rav1e -x-cargo --static

  macos:
 
    runs-on: macos-15

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg setup
      - run: ./ndk-pkg about
      - run: ./ndk-pkg update
      - run: ./ndk-pkg install android-35-arm64-v8a/rav1e -x-cargo --static
