name: ndk-pkg-brew-version-compare

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macos-11

    steps:
      - run: brew update
      - run: brew install perl
      - run: perl -V

      #- uses: actions/checkout@v2

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg

      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg --help
      - run: ./ndk-pkg env
      - run: ./ndk-pkg update
      - run: ./ndk-pkg test
