name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15
    
    strategy:
      fail-fast: false
      matrix:
        version: [8, 9]

    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/netbsd${{ matrix.version }}
        run: |
          run id
          run pkgin -y install mozilla-rootcerts
          run mozilla-rootcerts install
          run mozilla-rootcerts
          run ls -a /usr/pkg/etc/openssl/certs
          run ls -a /usr/pkg/share/mozilla-rootcerts
          run ls -a .
          run cp -r . ..
          run ls -a ..
