# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        version: [8, 9]

    env:
      VAGRANT_LOG: debug

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          run: |
            run export SSL_CERT_FILE="$PWD/cacert.pem"
            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install uppm
            run ./ppkg pack    uppm
