# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15
    
    strategy:
      fail-fast: false
      matrix:
        version: [8, 9]

    steps:
      - uses: actions/checkout@v2

      - run:  vagrant --version
      - run:  rm -rf ~/.vagrant.d

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          run: |
            run id
            run pkgin -y install mozilla-rootcerts
            run mozilla-rootcerts install
            run ls -a /usr/pkg/share/mozilla-rootcerts
            run ls -a .
            run cp -r . ..
            run ls -a ..
            run pkgin search tar
            run pkgin -y install gtar
            run gtar --version
