# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    env:
      VAGRANT_LOG: debug
    
    steps:
      - uses: actions/checkout@v2

      - run:  vagrant --version
      - run:  rm -rf ~/.vagrant.d

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/openbsd6
          run: |
            run ls
