name: openSUSE Leap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [15.1, 15.2]

    container: opensuse/leap:${{ matrix.tag }}

    steps:
      - run: zypper update -y
      - run: zypper install -y git

      - uses: actions/checkout@v2

      - run: zypper help info

      - run: zypper info cmake
      - run: zypper info make
      - run: zypper info git

      - run: |
          zypper info cmake | sed -n '/Version        :/p' | sed 's/Version        : \(.*\)/\1/' | cut -d- -f1

      - run: |
         zypper info   make | sed -n '/Version        :/p' | sed 's/Version        : \(.*\)/\1/' | cut -d- -f1

      - run: |
          zypper info   git | sed -n '/Version        :/p' | sed 's/Version        : \(.*\)/\1/' | cut -d- -f1

      - run: zypper info gitcdfg
