# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - run:  vagrant --version
      - run:  rm -rf ~/.vagrant.d

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/openbsd7
          run: |
            curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
            chmod a+x ppkg
            ./ppkg setup --use-system-package-manager

      - run: brew install openssh
      - run: command -v scp
