name: QEMU/NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        netbsd-version: ['10.0', '9.4', '9.3', '9.2']

    steps:
      - run: |
          cat > download.cmake <<EOF
          cmake_minimum_required(VERSION 3.15)

          message(STATUS "TRY 1")
          file(DOWNLOAD "https://raw.githubusercontent.com/cpp-pm/hunter-cache/master/8fd7dea/GTest/1.14.0/2b28c2a/297e0ef/4830b34/e5fa44f/basic-deps.DONE" "${CMAKE_CURRENT_BINARY_DIR}/basic-deps.DONE" TLS_VERIFY ON STATUS status LOG log)
          message("STATUS: ${status}")
          message("LOG: ${log}")


          message(STATUS "TRY 2")
          file(DOWNLOAD "https://raw.githubusercontent.com/cpp-pm/hunter-cache/master/8fd7dea/GTest/1.14.0/2b28c2a/297e0ef/4830b34/e5fa44f/basic-deps.DONE" "${CMAKE_CURRENT_BINARY_DIR}/basic-deps.DONE.2" TLS_VERIFY ON STATUS status LOG log)
          message("STATUS: ${status}")
          message("LOG: ${log}")
          EOF

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: ${{ matrix.netbsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y install cmake curl ca-certificates

            # https://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/security/ca-certificates/index.html
            run sudo /usr/pkg/sbin/update-ca-certificates -v --etccertsdir /etc/openssl/certs

            #export SSL_CERT_FILE='/etc/openssl/certs/ca-certificates.crt'

            run curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/caf.yml

            run cmake -P download.cmake
