name: run units target on a big endian architecture

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  s390x:
    runs-on: ubuntu-latest

    env:
      QEMU_S390X: ./proot -S alpine-s390x-rootfs -q qemu-s390x
      CC:       /home/runner/s390x-linux-musl-cross/bin/s390x-linux-musl-cc
      CPP:      /home/runner/s390x-linux-musl-cross/bin/s390x-linux-musl-cpp
      AR:       /home/runner/s390x-linux-musl-cross/bin/s390x-linux-musl-ar
      RANLIB:   /home/runner/s390x-linux-musl-cross/bin/s390x-linux-musl-ranlib
      CPPFLAGS: -I/home/runner/s390x-linux-musl-cross/s390x-linux-musl/include
      LDFLAGS:  -L/home/runner/s390x-linux-musl-cross/s390x-linux-musl/lib -static

    steps:
      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags

      - name: install alpine-s390x-rootfs
        run: |
          mkdir alpine-s390x-rootfs
          curl -LO https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/s390x/alpine-minirootfs-3.16.2-s390x.tar.gz
          tar xf alpine-minirootfs-3.16.2-s390x.tar.gz -C alpine-s390x-rootfs

      - name: install proot
        run: |
          curl -LO https://github.com/leleliu008/uppm-package-repository-linux-x86_64/releases/download/2022.09.23/proot-5.3.1-linux-x86_64.tar.xz
          tar vxf proot-5.3.1-linux-x86_64.tar.xz
          ln -s proot-5.3.1-linux-x86_64/bin/proot proot

      - name: install cross-compiler
        run: |
          curl -LO https://musl.cc/s390x-linux-musl-cross.tgz
          tar xf s390x-linux-musl-cross.tgz -C ~

      - run: sudo apt-get -y update
      - run: sudo apt-get -y install qemu-user automake autoconf pkg-config make

      - run: ./autogen.sh
      - run: |
          echo CC=$CC
          echo CPPFLAGS=$CPPFLAGS
          echo LDFLAGS=$LDFLAGS
          ./configure --enable-debugging CC=$CC || (cat config.log; exit 1)
      - run: make -j $(nproc)
      - run: ~/s390x-linux-musl-cross/bin/s390x-linux-musl-readelf -h ctags

      - run: $QEMU_S390X /sbin/apk update
      - run: $QEMU_S390X /sbin/apk add make git gdb procps findutils diffutils
      - run: $QEMU_S390X make check
