name: run units target on a big endian architecture

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  s390x:
    runs-on: ubuntu-latest

    env:
      PKGS: zlib-1.2.12 pcre2-10.40 libyaml-0.2.5 libxml2-2.10.2 libiconv-1.17 jansson-2.14
      CC:   /usr/bin/s390x-linux-gnu-gcc
      CPPFLAGS: -I/home/runner/pkg/include
      LDFLAGS:  -L/home/runner/pkg/lib
      PKG_CONFIG_PATH: /home/runner/pkg/lib/pkgconfig

    steps:
      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags

      - uses: actions/cache@v3
        id:   restore-cache
        with:
          path: /home/runner/pkg
          key:          dependent-packages-linux-s390x-glibc
          restore-keys: dependent-packages-linux-s390x-glibc

      - if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        run: |
          set -x

          mkdir -p /home/runner/pkg

          unset RELEASE_VERSION

          RELEASE_VERSION=$(curl -sL https://api.github.com/repos/leleliu008/uppm-package-repository-linux-s390x-glibc/releases/latest | jq -r .tag_name)

          for item in $PKGS
          do
            curl -LO https://github.com/leleliu008/uppm-package-repository-linux-s390x-glibc/releases/download/${RELEASE_VERSION}/${item}-linux-s390x-glibc.tar.xz
            tar xf ${item}-linux-s390x-glibc.tar.xz -C /home/runner/pkg --strip-components=1
          done

          rm -rf /home/runner/pkg/share/log
          rm -rf /home/runner/pkg/share/man
          rm -rf /home/runner/pkg/share/doc
          rm -rf /home/runner/pkg/share/gtk-doc
          rm -rf /home/runner/pkg/lib/libz.so*
          rm -rf /home/runner/pkg/lib/lib*.la
          rm -rf /home/runner/pkg/installed-files
          rm -rf /home/runner/pkg/installed-metadata-ppkg

      - run: sudo apt-get -y update
      - run: sudo apt-get -y install automake autoconf pkg-config make gcc-s390x-linux-gnu tree

      - run: ./autogen.sh
      - run: ./configure --host=s390x-ibm-linux-gnu --enable-debugging || (cat config.log; exit 1)
      - run: make -j$(nproc)

      - run: /usr/bin/s390x-linux-gnu-readelf -h ctags
      - run: /usr/bin/s390x-linux-gnu-readelf -d ctags

      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run apt -y update
          run apt -y install findutils diffutils

          #run git config --global --add safe.directory /home/runner/uctags

          run misc/units tmain --show-diff-output ./Tmain ./Tmain

          run misc/units run   --show-diff-output --run-shrink --with-timeout=10 ./Units ./Units
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v/home/runner/pkg:/home/runner/pkg -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }} s390x/ubuntu bash run.sh 
