name: build simplex-chat for linux

on:
  workflow_dispatch

jobs:
  simplex-chat:
    runs-on: ubuntu-latest
    container: alpine

    strategy:
      fail-fast: false
      matrix:
        version: ['6.2.5', '6.2.0', '6.1.1', '6.0.4']

    env:
      BOOTSTRAP_HASKELL_GHC_VERSION: 9.6.3
      BOOTSTRAP_HASKELL_CABAL_VERSION: 3.10.1.0
      BOOTSTRAP_HASKELL_NONINTERACTIVE: 1

    steps:
      - run: apk update
      - run: apk add curl git tar xz grep ghc-dev gmp-dev zlib-static zlib-dev openssl-libs-static openssl-dev alpine-sdk

      - run: ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfow.so.6

      - run: curl -LO https://github.com/simplex-chat/simplex-chat/archive/refs/tags/v${{ matrix.version }}.tar.gz
      - run: tar vxf *.tar.gz --strip-components=1

      - run: curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

      - run: |
          cat >> $GITHUB_PATH <<EOF
          $HOME/.cabal/bin
          $HOME/.ghcup/bin
          EOF

      - run: mv scripts/cabal.project.local.linux cabal.project.local

      - run: |
          sed -i '/extra-source-files:/a \  - PRIVACY.md' package.yaml

      - run: |
          sed -i '/- -Wunused-type-patterns/a\  - -O2\n\  - -split-sections\n\  - -with-rtsopts=-N\n\  - -static\n\cc-options: -static\n\ld-options: -static -pthread' package.yaml

      - run: cabal install --install-method=copy --installdir=/usr/local/bin hpack-0.36.0
      - run: hpack

      - run: cabal update
      - run: cabal v2-install --jobs=3 --install-method=copy --installdir=$PWD/out exe:simplex-chat

      - run: ls out/
      - run: readelf -d out/*

      - uses: actions/upload-artifact@v4
        with:
          name: simplex-chat-${{ matrix.version }}
          path: out/*
