name: build simplex-chat for linux

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: git clone git@github.com:simplex-chat/simplex-chat.git
      - run: cd simplex-chat
      - run: git checkout stable
      - run: DOCKER_BUILDKIT=1 docker build --output . .

