name: build simplex-chat for linux

on:
  workflow_dispatch

jobs:
  build1:
    if: false
    runs-on: ubuntu-latest

    steps:
      - run: |
          set -ex
          git clone https://github.com/simplex-chat/simplex-chat
          cd simplex-chat
          git checkout stable
          DOCKER_BUILDKIT=1 docker build --output . .

  build2:

    runs-on: ubuntu-latest

    steps:
      - run: |
          set -ex
          curl -LO https://github.com/simplex-chat/simplex-chat/archive/refs/tags/v6.0.4.tar.gz
          tar vxf v6.0.4.tar.gz
          cd simplex-chat-6.0.4
          DOCKER_BUILDKIT=1 docker build --output . .

