name: build simplex-chat for linux

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: |
          set -ex
          git clone https://github.com/simplex-chat/simplex-chat
          cd simplex-chat
          git checkout stable
          DOCKER_BUILDKIT=1 docker build --output . .

