name: Create a weekly tag

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

            #- run: git config user.name  'github-actions'
            #- run: git config user.email 'Universal-ctags@users.noreply.github.com'

      - run: git config user.name  'github-actions'
      - run: git config user.email 'opensource+cli@github.com'
      - run: git tag -a -m "Create a weekly tag" p6.0.20230706.0
      - run: git push origin p6.0.20230706.0
