name: Create a weekly tag

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - run: |
          cat git-rev-parse-HEAD-request > QUERY <<EOF
          {
            repository(owner: "universal-ctags", name: "ctags") {
              ref(qualifiedName: "refs/heads/master") {
                target {
                  oid
                }
              }
            }
          }
          EOF

      - run: git config user.name  'Universal-ctags GitHub Actions'
      - run: git config user.email 'Universal-ctags@users.noreply.github.com'

      - run: git tag -a -m "$(git rev-parse HEAD)" p6.0.20230706.0
      - run: git push origin p6.0.20230706.0
