name: Create a weekly tag

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git config user.name  'Universal-ctags GitHub Actions'
      - run: git config user.email 'Universal-ctags@users.noreply.github.com'

      - run: |
          HEAD="$(git rev-parse HEAD)"
          git tag -a -m "$HEAD\nhttps://github.com/universal-ctags/ctags/tree/$HEAD" p6.0.20230706.0
      - run: git push origin p6.0.20230706.0
