name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg

      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg env

      - run: ./ndk-pkg update

      - run: cp fortune.sh ~/.ndk-pkg/repos.d/offical/formula

      - run: echo "$XML_CATALOG_FILES"
      - run: apt -y install docbook-xsl
      - run: ls /etc/xml || true
      - run: ls /usr/share/xml/docbook/stylesheet || true
        #- run: |
        #apt-get -y install docbook-xsl docbook-xsl-ns
        #  brew install perl docbook-xsl
        # cpan -i App::Cpan
        # export PATH="$HOME/perl5/bin:$PATH"
        # export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
        # ./ndk-pkg install fortune --tree
