name: my own gcc on ubuntu

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['16.04', '18.04', '20.04', '21.04', '22.04', '23.04', '24.04', latest, edge]
 
    steps:
      - run: |
          cat > test.c <<EOF
          #include<stdio.h>
          int main() {
            puts("HELLO");
            return 0;
          }
          EOF
      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/gcc-13.1.0-linux-glibc-x86_64.tar.xz
      - run: tar xf gcc-13.1.0-linux-glibc-x86_64.tar.xz --strip-components=1

      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/binutils-2.41-linux-glibc-x86_64.tar.xz
      - run: tar xf binutils-2.41-linux-glibc-x86_64.tar.xz --strip-components=1

      - run: bin/gcc -Os -s -flto -static test.c
      - run: bin/readelf -h a.out
      - run: bin/readelf -d a.out
      - run: ./a.out
