# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: ubuntu

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: build.d

    steps:
      - uses: actions/checkout@v4

      - run: install -d build.d
        working-directory: ${{ github.workspace }}

      - run: pwd
      - run: ls ${{ github.workspace }}
