# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: ubuntu

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    container: ubuntu:18.04

    steps:
      - run: apt -y update
      - run: apt -y install gcc
      - run: gcc -print-file-name=libcrypt.a
      - run: gcc -print-file-name=libcrypt.so
      - run: gcc -print-file-name=libcrypt.so.1
