name: my own gcc on ubuntu

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['16.04', '18.04', '20.04', '21.04', '22.04', '23.04', '24.04', latest, edge]
 
    contianer: ubuntu:${{ matrix.version }}

    steps:
      - run: |
          cat > test.c <<EOF
          #include<stdio.h>
          int main() {
            puts("HELLO");
            return 0;
          }
          EOF
      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo

      - run: ~/.ndk-pkg/core/bin/gcc -Os -s -flto -static test.c
      - run: ~/.ndk-pkg/core/bin/readelf -h a.out
      - run: ~/.ndk-pkg/core/bin/readelf -d a.out

      - run: ./a.out
