name: publish uctags for openbsd-amd64

on:
  workflow_dispatch:

jobs:
  openbsd-amd64:

    runs-on: macos-12

    steps:
      - run: brew install openssh

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/openbsd7
          box-version: 4.2.16
          run: |
            run sudo pkg_add curl gtar-- gcc%11

            run sudo ln -s /usr/local/bin/gtar /usr/bin/tar

            export HOME=/home/vagrant
            export LD_LIBRARY_PATH=/usr/local/lib

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg
            run ./ppkg setup
            run ./ppkg update

            ~/.uppm/installed/gsed/bin/gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/uctags.yml

            run ./ppkg install uctags --link-type=static-full
            run ./ppkg pack    uctags -o /home/vagrant/

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/uctags-*-openbsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v3
        with:
          name: uctags---openbsd-amd64-tar-xz
          path: uctags-*-openbsd-amd64.tar.xz
