name: publish uctags

on:
  workflow_dispatch

jobs:
  netbsd-amd64:
    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/netbsd9
          run: |
            export HOME=/home/vagrant

            run sudo sed -i 's/#ETCCERTSDIR=/ETCCERTSDIR=/' /usr/pkg/etc/ca-certificates-dir.conf
            run sudo update-ca-certificates

            unset ETCCERTSDIR

            ETCCERTSDIR=$(sed -n '/^ETCCERTSDIR=/p' /usr/pkg/etc/ca-certificates-dir.conf | sed 's|ETCCERTSDIR=\(.*\)|\1|')

            if [ -n "$ETCCERTSDIR" ] ; then
                export SSL_CERT_FILE="$ETCCERTSDIR/ca-certificates.crt"
            fi

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --use-system-package-manager
            run ./ppkg update
            run ./ppkg install uctags --link-type=static-only --install-lib=static
            run ./ppkg pack    uctags

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/uctags-*-netbsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v2
        with:
          name: uctags-netbsd-amd64-tar-xz
          path: ${{ github.workspace }}/uctags-*-netbsd-amd64.tar.xz

  openbsd-amd64:
    needs: netbsd-amd64
    runs-on: macos-12

    steps:
      - run: brew install openssh

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/openbsd7
          run: |
            run sudo pkg_add curl

            export HOME=/home/vagrant
            export LD_LIBRARY_PATH=/usr/local/lib

            run sudo ln -sf /usr/local/bin/pkgconf /usr/bin/pkg-config

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --use-system-package-manager
            run ./ppkg update
            run ./ppkg install uctags --link-type=static-only --install-lib=static
            run ./ppkg pack    uctags

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/uctags-*-openbsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v2
        with:
          name: uctags-openbsd-amd64-tar-xz
          path: ${{ github.workspace }}/uctags-*-openbsd-amd64.tar.xz

  freebsd-amd64:
    needs: openbsd-amd64
    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/freebsd13
          run: |
            export HOME=/home/vagrant

            run pkg install -y curl libnghttp2

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
            run chmod a+x ppkg
            run ./ppkg setup --use-system-package-manager
            run ./ppkg update
            run ./ppkg install uctags --link-type=static-only --install-lib=static
            run ./ppkg pack    uctags

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/uctags-*-freebsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v2
        with:
          name: uctags-freebsd-amd64-tar-xz
          path: ${{ github.workspace }}/uctags-*-freebsd-amd64.tar.xz

  macos-x86_64:
    needs: freebsd-amd64
    runs-on: macos-latest

    env:
      ACLOCAL_PATH: /usr/local/share/aclocal
      MACOSX_DEPLOYMENT_TARGET: 10.15

    steps:
      - run: brew uninstall go@1.17
      - run: brew update
      - run: brew install --overwrite python@3.10 python@3.11

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup --use-system-package-manager
      - run: ./ppkg update
      - run: ./ppkg install uctags --link-type=static-prefered --install-lib=static
      - run: ./ppkg pack    uctags

      - uses: actions/upload-artifact@v2
        with:
          name: uctags-macos-x86_64-tar-xz
          path: ~/.ppkg/packed/uctags-*-macos-x86_64.tar.xz

  linux-x86_64:
    needs: macos-x86_64
    runs-on: ubuntu-latest

    container: alpine:3.16

    env:
      ACLOCAL_PATH: /usr/share/aclocal
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - run: apk update
      - run: apk add git

      - run: wget https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup --use-system-package-manager
      - run: ./ppkg update
      - run: ./ppkg install uctags gh --link-type=static-only --install-lib=static
      - run: ./ppkg pack    uctags

      - uses: actions/download-artifact@v2
        with:
          name: uctags-netbsd-amd64-tar-xz
          path: ~/.ppkg/packed/

      - uses: actions/download-artifact@v2
        with:
          name: uctags-openbsd-amd64-tar-xz
          path: ~/.ppkg/packed/

      - uses: actions/download-artifact@v2
        with:
          name: uctags-freebsd-amd64-tar-xz
          path: ~/.ppkg/packed/

      - uses: actions/download-artifact@v2
        with:
          name: uctags-macos-x86_64-tar-xz
          path: ~/.ppkg/packed/

      - run: ls -a
      - run: ls ~/.ppkg/packed

      - run: printf '%s\n' "$RELEASE_TOKEN" | ~/.ppkg/installed/gh/bin/gh auth login --with-token

      - run: git config --global --add safe.directory /__w/test/test

      - run: |
          printf '```\n%s```\n' "$(sha256sum ~/.ppkg/packed/uctags-*.tar.xz)" > notes.txt

          V=$(ls ~/.ppkg/packed/uctags-*-linux-x86_64.tar.xz | cut -d- -f2)

          ~/.ppkg/installed/gh/bin/gh release create $V ~/.ppkg/packed/* --notes-file notes.txt
