name: run units target on FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        freebsd-version: ['12.4', '13.3', '14.0', '14.1']

    steps:
      - uses: actions/checkout@v4
        with:
          repository: universal-ctags/ctags

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: ${{ matrix.freebsd-version }}
          run: |
            run() {
              printf '%s\n' "$*"
              eval "$@"
            }

            run pkg install -y automake pkgconf gmake python3
            run freebsd-version
            run cc --version
            run ./autogen.sh
            run ./configure --prefix=/usr
            run gmake
            run gmake install
            run file ctags
            run ctags --version
            run gmake check CI=gha+vagrant+freebsd
            run gmake roundtrip CI=gha+vagrant+freebsd
