name: uctags-build-tools tests on ubuntu

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['16.04', '18.04', '20.04', '22.04', '24.04', latest]
 
    container: ubuntu:${{ matrix.version }}


    steps:
      - run: apt -y update
      - run: apt -y install curl tar gzip xz-utils git

      - run: git clone --depth=1 https://github.com/universal-ctags/ctags

      - run: curl -LO https://github.com/leleliu008/uctags-build-tools/releases/download/2024.10.27/uctags-build-tools-2024.10.27-linux-glibc-x86_64.tar.xz
      - run: chmod +x uctags-build-tools-*.tar.xz

      - run: |
          export PATH="$PWD/uctags-build-tools-2024.10.27-linux-glibc-x86_64:$PATH"
          cd ctags
          ./autogen.sh
          ./configure
          gmake
          gmake install
