name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:

    strategy:
      fail-fast: false
      matrix:
        target: [MacOSX/10.15/x86_64, MacOSX/10.15/arm64, MacOSX/11.0/x86_64, MacOSX/11.0/arm64, MacOSX/12.0/x86_64, MacOSX/12.0/arm64]

    runs-on: macos-12

    steps:
      - run: brew uninstall go@1.17
      - run: brew update
      - run: brew install --overwrite python@3.10 python@3.11

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/dev/bin/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup --use-brew
      - run: ./xcpkg update
      - run: ./xcpkg install MacOSX/${{ matrix.target }}/uctags --link-type=static-prefered --install-lib=static
      - run: ./xcpkg pack    MacOSX/${{ matrix.target }}/uctags -o .

      - uses: actions/upload-artifact@v3
        with:
          name: uctags-${{ matrix.target }}-tar-xz
          path: ${{ github.workspace }}/uctags-*.tar.xz

