name: github-actions-upload-download-2

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg: [aria2, axel, base16, base64, bash, bat, bison, bc, bsdtar, bzip2, b3sum, cmake, coreutils, curl, darkhttpd, diffutils, dos2unix, ed, file, findutils, gawk, gperf, git, gm4, gmake, gh, grep, gsed, gtar, gzip, jq, lzip, lz4, nasm, ninja, openssl, patchelf, patch, pkgconf, pkg-config, pngquant, proot, putty, qpdf, rsync, rtmpdump, sqlite3, starship, strace, swig, tcpdump, tealdear, tig, tmux, tree, uctags, unrar, unzip, uppm, util-linux, xmake, xxd, xz, yasm, youtubedr, yq, zip, p7zip, zstd, zoxide, sysinfo, easyutils, gettext-tools, glib-tools, gindent, golang, go-md2man, grpc-plugins, xsltproc, libxml2-utils, figlet, lolcat]

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update
          run ./ppkg install ${{ matrix.pkg }} --link-type=static-full

          if [ -d ~/.ppkg/installed/${{ matrix.pkg }}/include ] ; then
              rm -rf               ~/.ppkg/installed/${{ matrix.pkg }}/include
              sed -i '/|include/d' ~/.ppkg/installed/${{ matrix.pkg }}/.ppkg/MANIFEST.txt
          fi

          if [ -d ~/.ppkg/installed/${{ matrix.pkg }}/lib ] ; then
              rm -rf           ~/.ppkg/installed/${{ matrix.pkg }}/lib
              sed -i '/|lib/d' ~/.ppkg/installed/${{ matrix.pkg }}/.ppkg/MANIFEST.txt
          fi

          ./ppkg pack ${{ matrix.pkg }} -o .


          PACKAGE_SUMMARY="\$(./ppkg info-installed ${{ matrix.pkg }} summary)"
          PACKAGE_WEB_URL="\$(./ppkg info-installed ${{ matrix.pkg }} web-url)"
          PACKAGE_VERSION="\$(./ppkg info-installed ${{ matrix.pkg }} version)"

          PACKAGE_BIN_FILENAME="${{ matrix.pkg }}-\$PACKAGE_VERSION-linux-x86_64.tar.xz"

          PACKAGE_BIN_SHA="\$(sha256sum "\$PACKAGE_BIN_FILENAME" | cut -d ' ' -f1)"

          PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-linux-x86_64/releases/download/@TAGNAME@/\${PACKAGE_BIN_FILENAME}"

          cat > ${{ matrix.pkg }}.yml <<EOF2
          summary: \$PACKAGE_SUMMARY
          webpage: \$PACKAGE_WEB_URL
          version: \$PACKAGE_VERSION 
          bin-url: \$PACKAGE_BIN_URL 
          bin-sha: \$PACKAGE_BIN_SHA
          EOF2

          EOF

          chmod +x run.sh

      - run: docker run -v "$PWD:$PWD" -w "$PWD" --name alpine alpine sh run.sh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ${{ matrix.pkg }}-*.tar.xz
            ${{ matrix.pkg }}.yml

  publish:
    needs: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:

      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: downloads
          merge-multiple: true

      - run: ls downloads

      - run: |
          # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
          git -c init.defaultBranch=master init
          git remote add origin ${{ github.repositoryUrl }}

          TAGNAME="$(date +%Y.%m.%d)"

          UPPM_FORMULA_ROOT_DIR="uppm-formula-repository-linux-x86_64-$TAGNAME"
          UPPM_FORMULA_DIR="$UPPM_FORMULA_ROOT_DIR/formula"

          cd downloads

          sed -i "s|@TAGNAME@|$TAGNAME|" *.yml

          install -d "$UPPM_FORMULA_ROOT_DIR/formula"
          mv *.yml   "$UPPM_FORMULA_ROOT_DIR/formula"
          tar cvJf   "$UPPM_FORMULA_ROOT_DIR.tar.xz" "$UPPM_FORMULA_ROOT_DIR"

          sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [ppkg](https://github.com/leleliu008/ppkg).

          these packages are statically linked against [musl-libc](https://musl.libc.org/).

          these packages are relocatable which means that you can install them to anywhere.

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md
