name: github-actions-upload-download

on:
  workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - run: |
          touch a.txt
          touch b.txt
          touch c.txt
      - uses: actions/upload-artifact@v4
        with:
          name: x.txt
          path: '*.txt'

  download:
    needs: upload
    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v4
        with:
          pattern: '*.txt'
          path: downloads
          merge-multiple: true
      - run: ls downloads
