name: publish uppm-freebsd

on:
  workflow_dispatch:
    #schedule:
    #- cron: '0 4 * * *'

jobs:
  freebsd-amd64:
    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/freebsd13
          run: |
            export HOME=/home/vagrant

            run pkg install -y curl libnghttp2

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg
            #run ./ppkg setup --use-system-package-manager
            run ./ppkg setup
            run ./ppkg update
            run ./ppkg install uppm --link-type=static-only --install-lib=static
            run ./ppkg pack    uppm

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/uppm-*-freebsd-amd64.tar.xz .
