name: macos10.15-x86_64-publish

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: macos-12

    env:
      GH_TOKEN: ${{ github.token }}
      PKG_NAMES: patchelf gettext-tools glib-tools grpc-plugins xsltproc libxml2-utils
      PLATFORM_VERSION: '10.15'

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup
      - run: ./xcpkg update
      - run: |
          for PKG_NAME in $PKG_NAMES
          do
            ./xcpkg install "MacOSX/$PLATFORM_VERSION/x86_64/$PKG_NAME" --link-type=static-prefered --install-lib=static
            ./xcpkg pack    "MacOSX/$PLATFORM_VERSION/x86_64/$PKG_NAME"
          done

      - run: |
          cd ~/.xcpkg/packed

          date +%Y.%m.%d > ts.txt

          TAGNAME="$(cat ts.txt)"

          UPPM_FORMULA_ROOT_DIR="uppm-formula-repository-macos$PLATFORM_VERSION-x86_64-$TAGNAME"
          UPPM_FORMULA_DIR="$UPPM_FORMULA_ROOT_DIR/formula"

          install -d "$UPPM_FORMULA_DIR"

          for PACKAGE_NAME in $PKG_NAMES
          do
              RECEIPT_FILEPATH="${HOME}/.xcpkg/installed/MacOSX/$PLATFORM_VERSION/x86_64/${PACKAGE_NAME}/.xcpkg/receipt.yml"

              PACKAGE_SUMMARY="$("${HOME}/.uppm/installed/yq/bin/yq" .summary "$RECEIPT_FILEPATH")"
              PACKAGE_WEB_URL="$("${HOME}/.uppm/installed/yq/bin/yq" .web-url "$RECEIPT_FILEPATH")"
              PACKAGE_VERSION="$("${HOME}/.uppm/installed/yq/bin/yq" .version "$RECEIPT_FILEPATH")"

              PACKAGE_BIN_FILENAME="$PACKAGE_NAME-$PACKAGE_VERSION-macos$PLATFORM_VERSION-x86_64.tar.xz"

              PACKAGE_BIN_SHA=$(~/.uppm/installed/coreutils/bin/sha256sum "$PACKAGE_BIN_FILENAME" | cut -d ' ' -f1)

              PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-macos$PLATFORM_VERSION-x86_64/releases/download/${TAGNAME}/${PACKAGE_BIN_FILENAME}"

              cat > "$UPPM_FORMULA_DIR/$PACKAGE_NAME.yml" <<EOF
          summary: $PACKAGE_SUMMARY
          webpage: $PACKAGE_WEB_URL
          version: $PACKAGE_VERSION
          bin-url: $PACKAGE_BIN_URL
          bin-sha: $PACKAGE_BIN_SHA
          EOF
          done

          tar cvJf "$UPPM_FORMULA_ROOT_DIR.tar.xz" "$UPPM_FORMULA_ROOT_DIR"

          ~/.uppm/installed/coreutils/bin/sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [xcpkg](https://github.com/leleliu008/xcpkg).

          these packages have no dependencies other than \`/usr/lib/lib*.dylib\` and \`/System/Library/Frameworks/*.framework\`.

          these packages are relocatable which means that you can install them to anywhere.

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
          git -c init.defaultBranch=master init
          git remote add origin ${{ github.repositoryUrl }}

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md
