name: VoidLinux-glibc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: voidlinux/voidlinux

    steps:
      - run: xbps-install -Sy git

      - uses: actions/checkout@v2

      - run: xbps-query cmake
      - run: xbps-query  make
      - run: xbps-query   git
      - run: xbps-query sfdad
