# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [2019, 2022]
        target-arch: [x86, amd64]

    runs-on: windows-${{ matrix.version }}

    defaults:
      run:
        shell: cmd /C {0}

    steps:
      - run: choco install -y file

      - uses: actions/checkout@v2
        with:
          repository: 'universal-ctags/ctags'

      - name: build
        run: |
          echo on
          if "${{ matrix.version }}" == "2019" (
            set XX= (x86)
          ) else (
            set XX=
          )

          echo %XX%
          @rem https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#developer_command_file_locations
          call "C:\Program Files%XX%\Microsoft Visual Studio\${{ matrix.version }}\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=${{ matrix.target-arch }}

          nmake -f mk_mvc.mak

      - run: file ctags.exe
