name: WSL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [Ubuntu-20.04, Debian, openSUSE-Leap-15.2]

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      # https://github.com/marketplace/actions/setup-wsl
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}

      - run: wsl --distribution ${{ matrix.distribution }} -u root ls /mnt/d/
        shell: pwsh

      - uses: actions/checkout@v2

      - run: pwd
      - run: ls
      - run: uname -a
      - run: env
      - run: ./ndk-pkg
