name: xcpkg

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: macos-13

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg env
      - run: ./xcpkg sysinfo
      - run: ./xcpkg setup
      - run: ./xcpkg update
      - run: ./xcpkg install exhale:MacOSX:10.15:x86_64 --link-type=static-prefered --install-lib=static
      - run: ./xcpkg pack    exhale:MacOSX:10.15:x86_64 -o .

      - uses: actions/upload-artifact@v3
        with:
          name: exhale-macos${{ matrix.target-version }}-${{ matrix.target-arch }}-tar-xz
          path: exhale-*.tar.xz


