name: xcpkg

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: macos-13

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg env
      - run: ./xcpkg sysinfo
      - run: ./xcpkg setup
      - run: ./xcpkg update
      - run: |
          ./xcpkg install MacOSX/10.15/x86_64/glib --link-type=static-prefered --install-lib=static || find ~/.xcpkg/run -name 'meson-log.txt' -printf '%p\n' -exec cat {} \;
      - run: ./xcpkg pack    MacOSX/10.15/x86_64/glib -o .

      - uses: actions/upload-artifact@v3
        with:
          name: glib-macos${{ matrix.target-version }}-${{ matrix.target-arch }}-tar-xz
          path: glib-*.tar.xz


