name: Build for Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'xmake-io/xmake'
          submodules: 'recursive'

      - run: brew install tree file xmake

      - run: tree  --version
      - run: file  --version
      - run: xmake --version

      - run: |
          cd core
          xmake config --clean -vD --mode=release --plat=android --arch=${{ matrix.abi }} --ndk_sdkver=21 --toolchain=ndk --ndk=$ANDROID_NDK_LATEST_HOME
          xmake
          xmake install -o ~/install.d

      - run: tree ~/install.d

      - run: |
          file ~/install.d/bin/xmake
          case ${{ matrix.abi }} in
            armv7a)  file ~/install.d/bin/xmake | grep 'ELF 32-bit LSB pie executable, ARM, EABI5'   ;;
            aarch64) file ~/install.d/bin/xmake | grep 'ELF 64-bit LSB pie executable, ARM aarch64,' ;;
            i686)    file ~/install.d/bin/xmake | grep 'ELF 32-bit LSB pie executable, Intel 80386,' ;;
            x86_64)  file ~/install.d/bin/xmake | grep 'ELF 64-bit LSB pie executable, x86-64,'      ;;
          esac
