name: Build for Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    runs-on: ${{ matrix.os }}

    env:
      ANDROID_NDK_HOME: $ANDROID_NDK_LATEST_HOME
      ANDROID_READELF:  $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf
      INSTALL_DIR: ${{ github.workspace }}/install.d
      SOURCE_DIR:  ${{ github.workspace }}/core
      BUILD_DIR:   ${{ github.workspace }}/build.d

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'xmake-io/xmake'
          submodules: 'recursive'

      - run: brew install tree file xmake

      - run: tree  --version
      - run: file  --version
      - run: xmake --version

      - run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          xmake config --clean -vD --mode=release --plat=android --arch=${{ matrix.abi }} --ndk_sdkver=21 --toolchain=ndk --ndk=$ANDROID_NDK_HOME --buildir=$BUILD_DIR --project=$SOURCE_DIR
          xmake
          xmake install -o      $INSTALL_DIR
          cp "$BUILD_DIR/xmake" $INSTALL_DIR/bin

      - run: tree ~/install.d

      - run: $ANDROID_READELF -d $INSTALL_DIR/bin/xmake

      - run: |
          file $INSTALL_DIR/bin/xmake
          case ${{ matrix.abi }} in
            armv7a)  file $INSTALL_DIR/bin/xmake | grep 'ELF 32-bit LSB pie executable, ARM, EABI5'   ;;
            aarch64) file $INSTALL_DIR/bin/xmake | grep 'ELF 64-bit LSB pie executable, ARM aarch64,' ;;
            i686)    file $INSTALL_DIR/bin/xmake | grep 'ELF 32-bit LSB pie executable, Intel 80386,' ;;
            x86_64)  file $INSTALL_DIR/bin/xmake | grep 'ELF 64-bit LSB pie executable, x86-64,'      ;;
          esac
