name: zig

on:
  workflow_dispatch:

jobs:
  ubuntu:

    strategy:
      fail-fast: false
      matrix:
        version: ['16.04', '18.04', '20.04', '22.04', '24.04']
 
    runs-on: ubuntu-latest
    container: ubuntu:${{ matrix.version }}

    steps:
      - run: apt update -y
      - run: apt install -y curl libarchive

      ###############################################################################

      - run: curl -LO https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2627+6a21d18ad.tar.xz
      - run: bsdtar xf zig-linux-x86_64-*.tar.xz --strip-components=1

      - run: |
          cat > test.c <<EOF
          #include<stdio.h>
          int main() {
            puts("Hello");
            return 0;
          }
          EOF

      - run: ./zig test.c
      - run: ./a.out

  alpine:

    strategy:
      fail-fast: false
      matrix:
        tag: ['3.21', '3.20', '3.19', '3.18', '3.17', '3.16', '3.15', '3.14', '3.13', '3.12']
 
    runs-on: ubuntu-latest
    container: alpine:${{ matrix.tag }}

    steps:
      - run: wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2627+6a21d18ad.tar.xz
      - run: tar xf zig-linux-x86_64-*.tar.xz --strip-components=1

      - run: |
          cat > test.c <<EOF
          #include<stdio.h>
          int main() {
            puts("Hello");
            return 0;
          }
          EOF

      - run: ./zig test.c
      - run: ./a.out
